FROM gradle:8.5-jdk17 AS build
WORKDIR /app

COPY . .

RUN chmod +x gradlew
RUN ./gradlew build

FROM eclipse-temurin:17-jdk
WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]